### PR TITLE
[Indigo] introduce launchfile argument for -J option of spawn_model

### PR DESCRIPTION
**Pull request by fmessmer**
This PR adds a new optional launch file argument for `cob_bringup_sim robot.launch` that allows to set joint to initial configs other than 0.0.
The argument can than be used like this:

```
roslaunch cob_bringup_sim robot.launch robot:=raw3-1 robot_env:=empty initial_config:='-J arm_shoulder_pan_joint 0.0 -J arm_shoulder_lift_joint -1.5707 -J arm_elbow_joint 0.0 -J arm_wrist_1_joint -1.5707 -J arm_wrist_2_joint 0.0 -J arm_wrist_3_joint 0.0'
```

(This feature is currently being re-added to `gazebo_ros_pkgs`....thus please hold this PR for a little longer...)

### CODE REVIEW

**Comment by floweisshardt** [comment]
is this really something we want the user of cob_bringup_sim to taglle with? although it is optional... I'd like to keep this high-level launch files as clean as possible.

I would rather define a reasonable start pose for all components on all robots, e.g. the default positions we park the robots and bring the robot automatically into that pose at startup.

**Comment by fmessmer** [comment]
Well, as it is optional, it's kind of an insider-feature.
But it's definitely interesting for all those using e.g cob3-7 or raw3-1 in order to get the universal_robot arm into a more suitable initial configuration...

> I would rather define a reasonable start pose for all components on all robots, e.g. the default positions we park the robots and bring the robot automatically into that pose at startup.

@ipa-fmw How would you do that? Using the "Wait-then-SSS"-script?

**Comment by floweisshardt** [comment]
I can't currently think of an easy way to implement that. So we'll probably stick to your suggestion using a launch file argument (with default="").

**Comment by NadiaHG** [comment]
Visual Review: Ok

**Comment by floweisshardt** [comment]
visual review: OK

**Pull request merged**
