### PR TITLE
change physic setings to improve simulation performance

### PR DESCRIPTION
**Pull request by abubeck**
This improves performance of the ipa-apartment a lot (factor 5). Works for me but has to be tested by others before merging.

### CODE REVIEW

**Comment by floweisshardt** [comment]
@ipa-nhg please test.

**Comment by floweisshardt** [comment]
@ipa-nhg could you already test it?

**Comment by abubeck** [comment]
I already got multiple requests from other simulation users for merging this PR. Could you please test and merge it.

**Comment by NadiaHG** [comment]
Tested : OK

**Comment by floweisshardt** [comment]
visual review: OK

**Pull request merged**
