### PR TITLE
Feature/switch assembly line sim to indigo

### PR DESCRIPTION
**Pull request by ipa-mig-mc**

### CODE REVIEW

**Comment by stefandoerr** [comment]
Looks good so far. Could you do a minor adaption by changing the color of the boxes on the belt to grey/black?

**Comment by fmessmer** [comment]
This PR is related to https://github.com/ipa320/cob_environments/pull/91

**Comment by stefandoerr** [comment]
tested it my pc.  :+1:

**Comment by fmessmer** [comment]
LGTM

**Pull request merged**
