### PR TITLE
add ikea kallax mesh

### PR DESCRIPTION
**Pull request by fmessmer**
mesh from Google SketchUp

### CODE REVIEW

**Comment by floweisshardt** [comment]
- please add urdf file 
- and add to `cob_gazebo_objects/test/urdf_object.test`

**Comment by fmessmer** [comment]
I only need the mesh for a collision object in `cob_obstacle_distance`....still added the URDF...

For a package overhaul there exists an issue #72

**Comment by floweisshardt** [comment]
we should use the spawn scripts from cob_bringup_sim and thus remove the launch file in this package

**Comment by fmessmer** [comment]
But for using those scripts [parameter information](https://github.com/ipa320/cob_environments/blob/indigo_dev/cob_default_env_config/ipa-apartment/object_locations.yaml) needs to be uploaded to the parameter server before:
...I want to upload any (urdf) model to any position at runtime
...also, I think spawn_object functionality should be within cob_gazebo_objects rather than cob_bringup_sim package

**Comment by NadiaHG** [comment]
+1 use only the spawn script to spawn objects and delete the launch file.
Anyway, if you want to create a new launch file, the file should be created in cob_bringup_sim. From my point of view, cob_gazebo_object should content only objects (urdfs and models).

**Comment by floweisshardt** [comment]
let's keep the launch file as proposed by @ipa-fxm. For the use case that you only want to spawn a single object from cob_gazebo_objects without adding it to the environment config (object_location.yaml).

**Pull request merged**
