### PR TITLE
[Indigo] fix environment to gazebo world frame + proper interia

### PR DESCRIPTION
**Pull request by fmessmer**
Now you cannot move the environment with the robot anymore as it is fixed to the Gazebo `world` frame.

### CODE REVIEW

**Comment by fmessmer** [comment]
@ipa-srd could you please test as just discussed in order to be safe that the `world` frame does no harm the navigation/localization?
You can cherry-pick 7a67995ee1b577040ffef50d8e0773da3d35b82c to a hydro version of cob_simulation!

**Comment by floweisshardt** [comment]
visual review:OK

**Comment by fmessmer** [comment]
I forgot to do the renaming in the `tf_publisher.py`

**Comment by floweisshardt** [comment]
visual review:OK

**Comment by stefandoerr** [comment]
tested with running navigation. looks good  :+1:

**Pull request merged**
