### PR TITLE
Fixed annoying Gazebo bug

### PR DESCRIPTION
**Pull request by ipa-frm-sd**
Fixed the issue with gazebo loading the robot before the world, so max range scans were published.

### CODE REVIEW

**Comment by fmessmer** [comment]
I see this bug is annoying, but with your proposed solution we are loosing the possibility to run 
`roslaunch cob_bringup_sim robot.launch` with launch file arguments, right?
If I want to use launch argument e.g. change my `robot` or `gui:=false` via launch argument, I would need to run the two gazebo_X.launch files separately...

**Comment by fmessmer** [comment]
Seems like someone also tries to fix the same problem, i.e. laser scans in gazebo, with the same proposed solution...[here](http://answers.ros.org/question/51474/can-i-run-a-bash-script-using-roslaunch/?answer=157051#post-id-157051)

**Comment by ipa-frm-sd** [comment]
@ipa-fxm  Fixed?! :-)

**Comment by fmessmer** [comment]
fixes #95 
Still, I don't like this "hack" too much...

**Comment by floweisshardt** [comment]
please don't merge. We should shoot for a proper fix

**Comment by fmessmer** [comment]
@ipa-frm-sd @ipa-srd @ipa-mig @ipa-flg (and all nav-students)
I haven't been able to reproduce the max_range behavior after I clone https://github.com/ros-simulation/gazebo_ros_pkgs/tree/indigo-devel into my workspace using `gazebo_ros_pkgs` from source (the laser plugins are in there!)

It might also be related to this fix https://github.com/ros-simulation/gazebo_ros_pkgs/pull/362, as the world model now spawns **much** faster!

This fix however is only available after `gazebo-ros` 2.4.10 is released (current version 2.4.9). Currently it waits for the next sync (http://repositories.ros.org/status_page/ros_indigo_default.html?q=gazebo_ros)

**Comment by ipa-flg** [comment]
Just to back @ipa-fxm : I just couldn't get rid of that error, not even with multiple restarts. As I cloned gazebo_ros_pkgs, as you suggested, performance was ok again

**Comment by mgruhler** [comment]
Well, if this is resolved with the new `gazebo_ros_pkgs`, I vote for closing this without merge. Seems cleaner to me...

**Comment by fmessmer** [comment]
I'll close it, once the release is out!

**Comment by fmessmer** [comment]
As experienced on @ipa-srd's PC, the work-around does not work all the time...still sometimes the world is spawned **after** the robot resultng in faulty max-range scans...

@ipa-srd currently investigates the `-wait` argument exposed by the `spawn_model` script (https://github.com/ros-simulation/gazebo_ros_pkgs/blob/indigo-devel/gazebo_ros/scripts/spawn_model#L51)

If this does not work, I think we should escalate this bug directly to https://github.com/ros-simulation/gazebo_ros_pkgs/issues

**Comment by floweisshardt** [comment]
closing this one as https://github.com/ipa320/cob_simulation/pull/111 proposed a cleaner solution

**Pull request closed without merging**
