### PR TITLE
move script for gazebo

### PR DESCRIPTION
**Pull request by floweisshardt**

### CODE REVIEW

**Comment by NadiaHG** [comment]
Please add the script to the install tags https://github.com/ipa320/cob_simulation/blob/indigo_dev/cob_bringup_sim/CMakeLists.txt#L13

**Comment by NadiaHG** [comment]
The stl files are not used. If the collada files define the same object, the stls can be deleted

**Comment by fmessmer** [comment]
considered @ipa-nhg's comments

tested in simulation

CR ok

**Comment by fmessmer** [comment]
...and a happy travis

**Pull request merged**
