### PR TITLE
add simulation for izs-carpark-top to cob_gazebo_worlds

### PR DESCRIPTION
**Pull request by jabbenseth**
simulation for the top parking deck

### CODE REVIEW

**Comment by ipa-fez** [comment]
One of the ramps is a bit wider than on the line map which makes the car jump when it switches between matching the outer walls and the ramp walls for localisation.

screenshot - 08 06 2017 - 11 04 02

**Comment by jabbenseth** [comment]
I double checked the positions of the walls and found no difference to the linemap.
A potential issue here is the line map which models the walls of the ramps as single lines (walls with no thickness). For gazebo they are modeled as walls with 20cm thickness, which fits better to the real world.

**Comment by jabbenseth** [comment]
close and reopen to trigger travis with new cob_android

**Review by stefandoerr — APPROVED** [review]

**Review by floweisshardt — CHANGES_REQUESTED** [review]
we once agreed to only support "default" environments listed in http://wiki.ros.org/care-o-bot#Robots.2BAC8-Care-O-bot.Environment_variables.

If we would merge this we would have to add support in all env-specific packages for that environment. That's an support overhead we back then tried to avoid.

**Comment by jabbenseth** [comment]
I intend to add the environment to cob_environments as well to have an "outdoor" environment which allows for larger robots.

imho it can match the requirements for a "default" environment.

**Comment by floweisshardt** [comment]
ok, that sounds good. so the question goes to the remaining admins at IPA (mainly @ipa-mig) if they are willing to support an additional environment.

**Comment by jabbenseth** [comment]
while this remains a question for the admins we (@ipa-srd @ipa-bnm @ipa-flg @ipa-fez @ipa-fke and @ipa-jba) had a short conversation and concluded we are willing to support the new environment

**Review by floweisshardt — CHANGES_REQUESTED** [review]
ok fine with adding this.

Minor change request: name for environment should be all lower case (no CAPS), e.g. izs-carpark-top

**Comment by jabbenseth** [comment]
however let's wait for next week and ask @ipa-mig about this

**Review by floweisshardt — APPROVED** [review]

**Review by benmaidel — APPROVED** [review]

**Review by mgruhler — APPROVED** [review]
I'm fine with this.

@ipa-fmw Can this be merged already or would you rather have the rest of the PRs for the "default"-env as well and merge together?

**Comment by floweisshardt** [comment]
merge together :-) otherwise the risk is high, that these PRs get lost...

**Comment by mgruhler** [comment]
@ipa-fmw which other repos/packages need PRs then?

- ipa320/cob_environments/cob_default_env_config
- ???

**Comment by floweisshardt** [comment]
one more is `ipa_navigation/ipa_navigation_environment_config` and `cob_navigation`

**Comment by mgruhler** [comment]
right about `ipa_navigation`. But what is to be done in `cob_navigation`? I did not find env specific config or launch files there...

**Comment by floweisshardt** [comment]
right, we can skip cob_navigation. The environment configuration for cob_navigation is in cob_default_env_config.

**Pull request merged**
