### PR TITLE
fix ipa-apartment elevetor controllers

### LINKED ISSUE #82: Shaking walls in ipa-apartment
@ipa-fxm @ipa-nhg 
Me and some of my students experienced some strange behaviors when simulating with the gazebo world ipa-apartment. From time to time the walls start shaking in a earth quake manner,  the doors of the elevators start walking around and sometimes whole areas are teleported to a different place.
In 'earth quake mode' there is nothing you can do than restart the whole simulation.

### PR DESCRIPTION
**Pull request by fmessmer**
fixes #82

### CODE REVIEW

**Comment by fmessmer** [comment]
@ipa-srd please test this

**Comment by floweisshardt** [comment]
visual review: OK
still waiting for feedback from @ipa-srd

**Comment by NadiaHG** [comment]
still not 100% right, at least in my case, the elevator buttons are still shaking.

**Comment by fmessmer** [comment]
The buttons or the doors?
Might be, I haven't tested it long enough
...maybe the collision of the buttons intersect with some wall or the door.
...or inertias/masses are still too high

Still, I never experienced the "earthquake" mode @ipa-srd reported...

@dabarsch you also started to fix this, right?
@ipa-mig: FYI

**Comment by dabarsch** [comment]
The buttons are now doing the same strange jumping inside the floor that the doors have done before. The doors themselves are fixed. Ipa-srd is on vacation for the next 2 weeks and I am the student who initially reported the bug to him.
Actually I don't know how to fix it, but I can reproduce it on my computer, so I could assist you.

**Comment by NadiaHG** [comment]
https://github.com/ipa320/cob_simulation/pull/84 this version is working but I had to define 0.0 inertias (¿?) , otherwise we have the "jumping" problem. what do you think @ipa-fxm  ?

I also renamed some joints, and adjusted the elevator script , now you can open the doors pressing the button.

I think we can delete the buttons controllers , we dont need it , the bumper just  need a transmission.

**Comment by fmessmer** [comment]
superseded by #84

**Pull request merged**
