### PR TITLE
retreat person object on obstacle

### PR DESCRIPTION
**Pull request by souravran**
provision for re-spawning the person object to the start, after a halt of 60 seconds, due to presence of obstacle

### CODE REVIEW

**Comment by souravran** [comment]
related to https://github.com/ipa320/msh_test/pull/3

**Review by fmessmer — CHANGES_REQUESTED** [review]
discussed some simplifications with @souravran 
waiting for additional commits

**Review by fmessmer — APPROVED** [review]
@souravran 
did you test in simulation? does it work as expected?

**Comment by souravran** [comment]
yes, works as expected in simulation.

**Review by floweisshardt — APPROVED** [review]

**Pull request merged**
