### PR TITLE
Final improvements to ipa-production-plant

### PR DESCRIPTION
**Pull request by ipa-srd-rd**
In this PR the new environment ipa-production-plant has been updated again. Objects used for the gazebo world, like the Reflector Marker or conveyor were added to cob_gazebo_objects.

Further the spawn_object script was modified such that 
- it can spawn sdf models  
- it's possible to specify groups of objects as an argument which will be spawned 
- error messages were reduced, because the script checks now whether a model is already spawned before it tries to delete it
- the structure was reduced to minimize redundance

This PR is based on https://github.com/ipa320/cob_simulation/pull/110
built up on https://github.com/ipa320/cob_simulation/pull/113
and related to https://github.com/ipa320/cob_environments/pull/109

### CODE REVIEW

**Comment by floweisshardt** [comment]
tested together with https://github.com/ipa320/cob_environments/pull/109

minor improvements/requests:
- modified spawn script to handle empty groups (e.g. ipa-apartment) --> done in https://github.com/ipa-srd-rd/cob_simulation/pull/1
- renamed groups namespace to /object_groups --> done in https://github.com/ipa-srd-rd/cob_environments/pull/2 and https://github.com/ipa-srd-rd/cob_simulation/pull/1
- extend remove_object.py to handle groups --> tdb by @ipa-srd-rd 
- enable roslaunch checks --> done in https://github.com/ipa-srd-rd/cob_environments/pull/2 and 
- remove some prints or convert to rospy.log\* in spawn_objects.py -- done in https://github.com/ipa-srd-rd/cob_simulation/pull/1
- remove duplicated upload_objects.launch in ipa-production-plant.launch --> done in https://github.com/ipa-srd-rd/cob_simulation/pull/1

comments:
- There are static laser transformations published as well as remaps for laser topics in ipa-production-plant but I can't see any laser topic beeing published. @ipa-mig: is this still used or a left-over from some old setup --> already done in https://github.com/ipa-srd-rd/cob_simulation/pull/1
- all objects are spawned at startup od cob_bringup_sim/robot.launch: this slows down gazebo up to "not usable anymore" on not so fast pcs. I'd recommend to not spawn any object an hand it over to the user to spawn objects (all/group/object). This is why we have this nice group feature now. @ipa-mig: what's your opinion? --> already done in https://github.com/ipa-srd-rd/cob_simulation/pull/1
- there is a hardcoded "moving object" spawned. I'd again reccomend to hand that over to the user to spawn objects and move them. the fork lifter can be integrated as a normal object in objects.yaml and even used within groups. move_object.py should not be in the default environment but again up to the user to move certain objects. --> already done in https://github.com/ipa-srd-rd/cob_simulation/pull/1
- there are different environments supported by cob_default_env_config and cob_gazebo_worlds. @ipa-mig: which environments do you still use? here's the overall list: 
  - automotive-assembly-line --> delete?
  - empty --> OK
  - ipa-apartment --> OK
  - ipa-factory --> delete?
  - ipa-kitchen --> OK
  - ipa-office --> keep?
  - ipa-production-plant --> OK

**Comment by stefandoerr** [comment]
Imo, ipa-factory can be deleted, but please keep automotive-assembly-line and ipa-office

**Comment by ipa-srd-rd** [comment]
- extend remove_object.py to handle groups  -> done!

**Comment by mgruhler** [comment]
@ipa-fmw Travis is crashing with the roslaunch checks... Do you know what the problem is?

**Comment by mgruhler** [comment]
> There are static laser transformations published as well as remaps for laser topics in ipa-production-plant but I can't see any laser topic beeing published. @ipa-mig: is this still used or a left-over from some old setup --> already done in ipa-srd-rd#1

I'm not sure about this one. @ipa-srd?

**Comment by floweisshardt** [comment]
travis says:

```
roslaunch.depends.RoslaunchDepsException: Cannot load roslaunch include '/home/travis/catkin_ws/install/share/cob_gazebo_worlds/launch/!!NO_ROBOT_ENV_SET!!.launch' in '/home/travis/catkin_ws/install/share/cob_gazebo_worlds/launch/world.launch'
```

this means that we try to load ROBOT_ENV within a launch file, but the environment variable is not set. should be set in https://github.com/ipa-srd-rd/cob_simulation/blob/feature/ipa_production_plant_final/cob_gazebo_worlds/CMakeLists.txt#L26. I will have to investigate that tomorrow.

**Comment by mgruhler** [comment]
> all objects are spawned at startup od cob_bringup_sim/robot.launch: this slows down gazebo up to "not usable anymore" on not so fast pcs. I'd recommend to not spawn any object an hand it over to the user to spawn objects (all/group/object). This is why we have this nice group feature now. @ipa-mig: what's your opinion? 

:+1:

> there is a hardcoded "moving object" spawned. I'd again reccomend to hand that over to the user to spawn objects and move them. the fork lifter can be integrated as a normal object in objects.yaml and even used within groups. move_object.py should not be in the default environment but again up to the user to move certain objects. --> already done in ipa-srd-rd#1

:+1:  for handing this over to the user. But how should we specify predefined trajectories in specific environments? As the trajectories have to be passed in over the command line we could have seperate launch files each (e.g. `move_object_straight.launch`. ...) Or we could rewrite `move_object.py` to read in the data from a yaml instead, which I would prefer. Then we can have one launch file and several, env specific trajectories that we launch. @ipa-fwm, what do you think?

> there are different environments supported by cob_default_env_config and cob_gazebo_worlds. @ipa-mig: which environments do you still use?

what @ipa-srd said :-)

**Comment by stefandoerr** [comment]
> There are static laser transformations published as well as remaps for laser topics in ipa-production-plant but I can't see any laser topic beeing published. @ipa-mig: is this still used or a left-over from some old setup --> already done in ipa-srd-rd#1
> 
> I'm not sure about this one. @ipa-srd?

Doesn't it say 

> --> already done in ipa-srd-rd#1

? ;)

**Pull request merged**
